version: '3'

services:
  php:
    image: php:fpm-buster
    container_name: streamideo_php
    volumes:
      - ./cinema:/usr/share/nginx/app
      - ./storage-manager:/usr/share/nginx/storage
    ports:
      - ${PHP_FPM_PORT}:9000
  mysql:
    image: mysql:5.7
    container_name: streamideo_db
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./env/mysql/init:/docker-entrypoint-initdb.d
      - ./env/mysql/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=streamideo
      - MYSQL_PASSWORD=streamideo
      - MYSQL_DATABASE=streamideo
  streamideo:
    build: ./streamideo
    container_name: streamideo
    volumes:
      - ./env/php/embed/php.ini:/etc/php/8.0/embed/php.ini
      - ./env/nginx:/etc/nginx
    ports:
      - ${STREAM_APP_PORT}:80
    links:
      - php
      - mysql
  storage-manager:
    build: ./storage-manager
    container_name: streamideo_storage
    ports:
      - ${STORAGE_MANAGER_PORT}:80
    volumes:
      - ./storage-manager:/usr/share/nginx/storage
      - ./env/sites/storage-manager.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
  cinema:
    container_name: streamideo_web
    build: ./
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./cinema:/usr/share/nginx/app
      - ./env/sites/cinema.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
