version: '3'

services:
  php:
    image: php:fpm-buster
    ports:
      - ${PHP_FPM_PORT}:9000
  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./env/logs/mysql.log:/var/log/mysql/mysql.log
  streamideo:
    build: ./streamideo
    volumes:
      - ./env/php/embed/php.ini:/etc/php/8.0/embed/php.ini
      - ./env/nginx:/etc/nginx
    ports:
      - ${APP_PORT}:80
    links:
      - php
      - mysql
